### PR TITLE
feat: add btrfs storage extension

### PR DESCRIPTION
**Pull request by Gottox**
Part 2 of 2 to add a btrfs extension to talos.

tracking issue: https://github.com/siderolabs/extensions/issues/199

### CODE REVIEW

**Comment by frezbo** [comment]
Could you also add a README in the btrfs folder?

**Comment by Gottox** [comment]
> Could you also add a README in the btrfs folder?

Added.

**Review by frezbo — APPROVED** [review]

**Comment by Gottox** [comment]
I don't get why it failed for non-free. Is that an issue in the pipeline?

**Comment by frezbo** [comment]
> I don't get why it failed for non-free. Is that an issue in the pipeline?

yes, that's my mistake, merging the previous PR, fixes coming

**Pull request merged**
