### PR TITLE
Upgrade KATA_CONTAINERS to 3.9.0

### PR DESCRIPTION
**Pull request by hh**
3.3 is a bit old, we are needing some features from 3.9

### CODE REVIEW

**Comment by hh** [comment]
All the other runtime extensions appear to be at the current version other than kata_containers.

**Comment by BobyMCbobs** [comment]
may resolve
https://github.com/siderolabs/extensions/issues/424

**Comment by smira** [comment]
As long as it works, we're happy to update, but it was broken last time we checked. Does it work with 3.9.0 for you?

**Comment by hh** [comment]
We'll check today. Do you remember what issues you encountered?

**Comment by smira** [comment]
> We'll check today. Do you remember what issues you encountered?

it's in the #424, but basically it doesn't pass a simple test which spins up a pod with kata

**Comment by BobyMCbobs** [comment]
@frezbo, do you have any recommendations for testing these changes?

**Comment by frezbo** [comment]
> @frezbo, do you have any recommendations for testing these changes?

you can use the imager with the upgraded extension to generate an installer image

**Comment by frezbo** [comment]
Closing as duplicate of #424

**Pull request closed without merging**
