### PR TITLE
fix: nvidia fabricmanager production

### PR DESCRIPTION
**Pull request by frezbo**
Fix NVIDIA FabricManager production.

Fixes: #511

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by abckey** [comment]
it seems:
```nv-fabricmanager --config /usr/local/share/nvidia/nvswitch/fabricmanager.cfg```
is not enough

```FABRIC_NODE_CONFIG_FILE=/usr/local/share/nvidia/nvswitch/fabricmanager.cfg```
needs also to be added to fabricmanager.cfg

**Comment by frezbo** [comment]
> it seems: `nv-fabricmanager --config /usr/local/share/nvidia/nvswitch/fabricmanager.cfg` is not enough
> 
> `FABRIC_NODE_CONFIG_FILE=/usr/local/share/nvidia/nvswitch/fabricmanager.cfg` needs also to be added to fabricmanager.cfg

is it needed? with the changes on an A100 it was working fine

**Comment by abckey** [comment]
> > it seems: `nv-fabricmanager --config /usr/local/share/nvidia/nvswitch/fabricmanager.cfg` is not enough
> > `FABRIC_NODE_CONFIG_FILE=/usr/local/share/nvidia/nvswitch/fabricmanager.cfg` needs also to be added to fabricmanager.cfg
> 
> is it needed? with the changes on an A100 it was working fine

after mounting `/usr/local/share/nvidia/nvswitch` as `/usr/share/nvidia/nvswitch`, then it is not needed to add `FABRIC_NODE_CONFIG_FILE`  into `fabricmanager.cfg` , but I guess that is just a workaround since FABRIC_NODE_CONFIG_FILE is default to `/usr/share/nvidia/nvswitch/fabricmanager.cfg` if not defined. Proper fix seems to be defining it into fabricmanager.cfg.

I tested one self-generated extension with only adding  `FABRIC_NODE_CONFIG_FILE=/usr/local/share/nvidia/nvswitch/fabricmanager.cfg`  into  fabricmanager.cfg, on one H100, it works fine

**Comment by frezbo** [comment]
thanks, I guess it was not a default config, will fix for 1.10

**Comment by frezbo** [comment]
> thanks, I guess it was not a default config, will fix for 1.10

Actually pulling for 1.9 too #554

**Pull request merged**
