### PR TITLE
feat: add mdmon to mdadm extension

### PR DESCRIPTION
**Pull request by dnugmanov**
In Intel VROC setups, maintaining the integrity of imsm metadata is essential. mdmon plays a pivotal role in ensuring the efficiency of metadata management. Our PR incorporates mdmon into the directory alongside mdadm. This integration guarantees proper functionality in Intel VROC environments

### CODE REVIEW

**Comment by frezbo** [comment]
I guess it also needs to run as a daemon?

**Comment by dnugmanov** [comment]
Hi, @frezbo 

> I guess it also needs to run as a daemon?

mdadm runs itself if needed. mdadm tries to find binary file and the start it via systemctl or directly - [source code](https://github.com/neilbrown/mdadm/blob/5f4184557a98bb641a7889e280265109c73e2f43/util.c#L1916).

> is there a way to test it's functionality or needs some specific hardware?

In my case it is specific hardware, Intel VROC supported.

My case:
```
nsenter --mount=/proc/1/ns/mnt -- mdadm --create /dev/md/imsm0 /dev/nvme[0-2]n1 --raid-devices=3 --metadata=imsm
nsenter --mount=/proc/1/ns/mnt -- mdadm --create /dev/md/md0 /dev/md/imsm0 --raid-devices=3 --level=5 
```

**Review by frezbo — APPROVED** [review]

**Pull request merged**
