### PR TITLE
release(v1.3.7): prepare release

### PR DESCRIPTION
**Pull request by smira**
This is the official v1.3.7 release.

### CODE REVIEW

**Review by frezbo — APPROVED** [review]
also needs go version bump in `nvida-gpu/vars.yaml`

**Comment by smira** [comment]
> also needs go version bump in `nvida-gpu/vars.yaml`

it's using 1.17.13... I'm not sure if I can bump it?

**Comment by frezbo** [comment]
> > also needs go version bump in `nvida-gpu/vars.yaml`
> 
> it's using 1.17.13... I'm not sure if I can bump it?

sorry, i assumed this was on main

**Review by frezbo — APPROVED** [review]

**Pull request merged**
