### PR TITLE
fix: set `DATABASE_PATH` for fabricmanager

### PR DESCRIPTION
**Pull request by frezbo**
This fixes fabricmanager crashing.

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
I guess we should backport it to v1.5 and v1.6?

**Comment by frezbo** [comment]
> I guess we should backport it to v1.5 and v1.6?

yes, not sure about 1.5, that must be an old driver

**Comment by smira** [comment]
> > I guess we should backport it to v1.5 and v1.6?
> 
> yes, not sure about 1.5, that must be an old driver

I think the problem was first reported in 1.5.x Talos.

**Comment by jpuyobro** [comment]
Yes, the problem was reported using the nvidia version 535.54.03. And this version is proposed for talos 1.5

**Comment by frezbo** [comment]
> Yes, the problem was reported using the nvidia version 535.54.03. And this version is proposed for talos 1.5

Thanks for confirming, I'll get it backported too.

**Pull request merged**
